/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Response2002 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5353944661127862L;
    private int balance;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("balance")
    public int getBalance ( ) { 
        return this.balance;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("balance")
    public void setBalance (int value) { 
        this.balance = value;
    }
 
}
