/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform.models;

import java.util.*;

public class Response2002Builder {
    //the instance to build
    private Response2002 response2002;

    /**
     * Default constructor to initialize the instance
     */
    public Response2002Builder() {
        response2002 = new Response2002();
    }

    public Response2002Builder balance(int balance) {
        response2002.setBalance(balance);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Response2002 build() {
        return response2002;
    }
}