/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform.models;

import java.util.*;

public class Response2001Builder {
    //the instance to build
    private Response2001 response2001;

    /**
     * Default constructor to initialize the instance
     */
    public Response2001Builder() {
        response2001 = new Response2001();
    }

    public Response2001Builder id(String id) {
        response2001.setId(id);
        return this;
    }

    public Response2001Builder senderName(String senderName) {
        response2001.setSenderName(senderName);
        return this;
    }

    public Response2001Builder phoneNumber(String phoneNumber) {
        response2001.setPhoneNumber(phoneNumber);
        return this;
    }

    public Response2001Builder status(int status) {
        response2001.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Response2001 build() {
        return response2001;
    }
}