/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform.models;

import java.util.*;

public class Response200Builder {
    //the instance to build
    private Response200 response200;

    /**
     * Default constructor to initialize the instance
     */
    public Response200Builder() {
        response200 = new Response200();
    }

    public Response200Builder id(String id) {
        response200.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Response200 build() {
        return response200;
    }
}