/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import com.releans.platform.*;
import com.releans.platform.models.*;
import com.releans.platform.exceptions.*;
import com.releans.platform.http.client.HttpClient;
import com.releans.platform.http.client.HttpContext;
import com.releans.platform.http.request.HttpRequest;
import com.releans.platform.http.response.HttpResponse;
import com.releans.platform.http.response.HttpStringResponse;
import com.releans.platform.http.client.APICallBack;
import com.releans.platform.controllers.syncwrapper.APICallBackCatcher;

public class BalanceController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static BalanceController instance = null;
    
    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the BalanceController class 
     */
    public static BalanceController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new BalanceController();
                }
            }
        }
        return instance;
    }

    /**
     * Get your available balance
     * @param    accept    Required parameter: Example: 
     * @return    Returns the Response2002 response from the API call 
     */
    public Response2002 getBalance(
                final String accept
    ) throws Throwable {
        APICallBackCatcher<Response2002> callback = new APICallBackCatcher<Response2002>();
        getBalanceAsync(accept, callback);
        if(!callback.isSuccess()) {
            throw callback.getError();
        }
        return callback.getResult();
    }

    /**
     * Get your available balance
     * @param    accept    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void getBalanceAsync(
                final String accept,
                final APICallBack<Response2002> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                final HttpRequest _request;

                try {
                    //the base uri for api requests
                    String _baseUri = Configuration.getBaseUri();

                    //prepare query string for API call
                    StringBuilder _queryBuilder = new StringBuilder("/balance");

                    //validate and preprocess url
                    String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                    //load all headers for the outgoing API request
                    Map<String, String> _headers = new HashMap<String, String>();
                    _headers.put("Accept", accept);

                    _headers.put( "Authorization", String.format("Bearer %1$s", Configuration.oAuthAccessToken) );
                    _headers.put("user-agent", BaseController.userAgent);


                    //prepare and invoke the API call request to fetch the response
                    _request = getClientInstance().get(_queryUrl, _headers, null);

                    //invoke the callback before request if its not null
                    if (getHttpCallBack() != null) {
                        getHttpCallBack().OnBeforeRequest(_request);
                    }

                } catch (Throwable e) {
                    callBack.onFailure(null, e);
                    return;
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {


                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null) {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            Response2002 _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<Response2002>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null) {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}