/*
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.releans.platform;

import com.releans.platform.controllers.*;
import com.releans.platform.http.client.HttpClient;

public class ReleansAPIClient {
    /**
     * Singleton access to Message controller
     * @return	Returns the MessageController instance 
     */
    public MessageController getMessage() {
        return MessageController.getInstance();
    }

    /**
     * Singleton access to Sender controller
     * @return	Returns the SenderController instance 
     */
    public SenderController getSender() {
        return SenderController.getInstance();
    }

    /**
     * Singleton access to Balance controller
     * @return	Returns the BalanceController instance 
     */
    public BalanceController getBalance() {
        return BalanceController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public ReleansAPIClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public ReleansAPIClient(String oAuthAccessToken) {
        this();
        Configuration.oAuthAccessToken = oAuthAccessToken;
    }
}